### ISSUE TITLE
IAAFSelector Member Functions

### ISSUE THREAD

**Issue by Toadman30** [markreidvfx/pyaaf#12]
Hello,

I was wondering if you could add the rest of the functions for AAF Selector Class?

Thanks
Matt

**Comment by markreidvfx** [comment]
I just added the rest of methods in c615afe764aad46e724d03ee38c4f1b67cf2d0a5

**Comment by Toadman30** [comment]
Thank You!

**Comment by Toadman30** [comment]
I'm having trouble making a SourceClip the selected segment. Basically I am trying to make a "group clip" with two SourceClips. In the Avid you can make multi-cam group clips. One as the Selected and the other as the alternative.

**Comment by markreidvfx** [comment]
the error code doesn't really help too much, I see you just modifying the create sequence test, can you post the code so I can see if I can replicate it? you might want to try setting the selector.media_kind = "picture" before adding to to the sequence

**Comment by Toadman30** [comment]
f = aaf.open(output_aaf, "w")
        
        video_rate = " 24000/1000"
        
        comp_mob = f.create.CompositionMob()
        sequence1 = f.create.Sequence("picture")
        sequence2 = f.create.Sequence("picture")
        
        timeline_slot1 = comp_mob.append_new_timeline_slot(video_rate, sequence1)
        timeline_slot2 = comp_mob.append_new_timeline_slot(video_rate, sequence2)

        f.storage.add_mob(comp_mob)
        TAPE_LENGTH  = 1 * 60 *60 * 30
        file_len = 60 * 30 
        filler_len = 48
        tape_tc = aaf.util.Timecode(108000, "NonDrop", 24)

-------------------------------------------------------------------------------------------


            # Creare Selector
            selector = f.create.Selector()
            selector.media_kind = "picture"
            sequence2.append(selector)

Everything else is the same from your create sequence. I can send you an aaf with a groupclip on it if you'd like.

**Comment by Toadman30** [comment]
Was wondering if you ever had time to look this over?
