### ISSUE TITLE
Locator cannot be instantiated from Python

### ISSUE THREAD

**Issue by sugarfixx** [markreidvfx/pyaaf#15]
Not sure if I am doing this right as I am pretty rusty in Python these days.
I try to add Locators / NetworkLocators to the essence using "descriptor.append_locator()" in the SourceMob but only get wrong argument expecting aaf.essence.Locator or Locator cannot be instantiated fromPython.

**Comment by markreidvfx** [comment]
Locator is a abstract class and therefore cannot be instantiated, but the NetworkLocator can be.
to create one try

f = aaf.open()
locator = f.create.NetworkLocator()
