### ISSUE TITLE
Setting start/end and mark In/Out on source clip

### ISSUE THREAD

**Issue by ylathouris** [markreidvfx/pyaaf#16]
Hello, 

We are having some issues setting the source start/end and mark in/out for a clip in Avid. 

We are trying to facilitate a workflow between Maya and Avid Media Composer. In Maya, an artist will create a 3D sequence using storyboards as reference material. The output from Maya is an EDL-like file and a set of shot-based image sequences. The image sequences are converted to raw DNxHD video streams and that is what we're using to build the AAF with the pyaaf library.

The start frame of each image sequence is usually some number greater than zero (i.e. frame range: 100-200). If possible, we would like to preserve the original frame ranges when creating the AAF. This is important because it allows us to update the Maya sequence after the editor has worked on it in Avid Media Composer. Is it possible to set the start/end of the source media, as well as the mark in/out when building an AAF using pyaaf? 

We are considering embedding a start timecode in the raw DNxHD video streams but I am hoping there is another way. 

For your reference, this is roughly the code we're using:

```python

frame_rate = 24

aaf_file = aaf.open('/foo/bar/baz.aaf', 'w')

factory = aaf_file.dictionary
storage = aaf_file.storage

composition_mob = factory.create.CompositionMob('my_sequence')
storage.add_mob(composition_mob)

# Build sequence.
sequence = factory.create.Sequence('Picture')

# Build track.
track_number = 0
composition_mob.append_new_timeline_slot(
    frame_rate,
    sequence,
    slotID=track_number
)

# Build clip.
master_mob = factory.create.MasterMob(clip.name)
storage.add_mob(master_mob)

# Build essence.
master_mob.import_video_essence('/foo/bar/baz.dnxhd', frame_rate)

# Build source clip (i.e. frame range: 100-200).
timeline_mob_slot = master_mob.slots()[-1]
slot_id = timeline_mob_slot.slotID

# Set in/out (i.e. 8 frame handles)
timeline_mob_slot.mark_in = 108
timeline_mob_slot.mark_out = 193

start = 100
duration = 101
source_clip = master_mob.create_clip(slot_id, duration, start)

sequence.append(source_clip)
```

I'm pretty sure this actually results in an **Insufficient Media Error** in Avid Media Composer but hopefully it gives you an idea of what we are trying to achieve. 

Cheers

**Comment by ylathouris** [comment]
This is what I came up with:

```python
# Build essence.
master_mob.import_video_essence('/foo/bar/baz.dnxhd', frame_rate)

# Build source clip (i.e. frame range: 100-200).
timeline_mob_slot = master_mob.slots()[-1]

# Add timecode slot to allow for non-zero source media start/end values.
timecode = factory.create.Timecode(
    101,  # duration
    8,  # mark in
    frame_rate
)

master_mob.append_new_timeline_slot(frame_rate, timecode)
```

Not sure if this is the recommended way but this seems to work.

**Comment by markreidvfx** [comment]
Thats the fast and simple way to do, but if you need reel_names take a look at
https://github.com/markreidvfx/pyaaf/blob/b37699aa0e3285c9cb86454fb9c46451e74fb0fd/example/link_external_mxf.py#L111

when you use import_video_essence it creates a structure like this (simplified, without tracks and sequences)
MasterMob->SourceMob(CDCIDescriptor)

if you need a reel name you need to add a SourceMob to a track on the CDCIDescriptor Mob.
typically avid lays them out like this (again simplified)
MasterMob->SourceMob(CDCIDescriptor)->SourceMob(TapeDescriptor)
The  Mob.name of the TapeDescriptorMob is the reel name. 

when I get a chance, I'll update the import_media.py example to add reel_names and start timecode.
