### ISSUE TITLE
add property

### ISSUE THREAD

**Issue by gone-fishing** [markreidvfx/pyaaf#25]
I am trying to add in some metadata to an aaf that would appear in a custom column of a subclip in an Avid bin.
I have created the column in avid and exported a subclip  to see if I can find it using your code. 
By working thru the composition_mobs then finding the key that has a value of Usage_SubClip, then the key that has a value of UserComments I get to aaf.property.TaggedValue. from there I can access the info I put in the subclip column in avid. 
My goal is that I want to be able to do this in reverse. To add metadata to an aaf of a subclip. 
How do I create another aaf.property.TaggedValue?
I am obviously not a programmer and I am fumbling along, any help would be appreciated.
Thanks in advance.

**Comment by Toadman30** [comment]
In "test_file_io.py" it demonstrates how to do just this.

`def test_create_comments(self):
        test_file = os.path.join(sandbox, 'comments_create.aaf')
        f = aaf.open(test_file, 'w')

        header = f.header
        d = f.dictionary

        mob = d.create.MasterMob("bob")
        f.storage.add_mob(mob)

        d = {'comment1':'value1', 'comment2': "value2", 'comment3':"value3"}
        for key, value in d.items():
            mob.append_comment(key,value)

        for item in mob.comments():
            print('**', item.name, item.value)
            assert d[item.name] == item.value

        mob.remove_comment_by_name('comment3')

        for item in mob.comments():
            assert item.name != 'comment3'

        f.save()
        f.close()`


You would replace "mob = d.create.MasterMob("bob")" with your masterMob that was create from the Avid.

**Comment by gone-fishing** [comment]
thanks, ill give it a go

**Comment by gone-fishing** [comment]
got it working, thanks
