### ISSUE TITLE
Top level composition

### ISSUE THREAD

**Issue by rolodub** [markreidvfx/pyaaf#27]
Hi,
I cannot find the way to create a top_level composition.
When i create a CompositionMob, there is no UsageCode property.
I don't understand how to set a new UsageCode property to Usage_TopLevel for a CompositionMob.
Have you any clue?
Thanks!

**Comment by rolodub** [comment]
Hello,
I seems not implemented? 
When I type:
`comp = self.f.create.CompositionMob("Comp Example")
comp["UsageCode"].value = "Usage_TopLevel"`
It says:
NotImplementedError: set value method not implemented for type <aaf.define.TypeDefExtEnum object at 0x1084904b0>

Is there another way to set UsageCode property?
Thanks

**Comment by Toadman30** [comment]
No, it is not implemented. You can add it yourself and recompile.

Here is the info from the AAF COM API
> HRESULT IAAFMob2::SetUsageCode	(	[in] aafUID_constref 	usageCode	)	
> Set this mob's usage code.
> 
> Usage codes are documented in the AAF Edit Protocol, and related specifications.
> 
> Return codes:
> 
> AAFRESULT_SUCCESS
> 
> Parameters:
> usageCode	[in] The usage code value.
>
>


Import **ExtEnumDefMap** onto your mob.pyx


Then in the AAF.pxd on line 884 add the following:

`HRESULT SetUsageCode(aafUID_constref usageCode)`


Then add the property to the Mob.pyx

```
    property set_usage_code:
        def __set__(self, usage):
            cdef AUID auid = ExtEnumDefMap["usage_%s" % usage.lower()]
            error_check(self.mob2_ptr.SetUsageCode(auid.get_auid()))
```

**Comment by rolodub** [comment]
Ok, it seems i must cross a new level in my python practice! Compilation...
Thanks a lot!

**Comment by markreidvfx** [comment]
In the dev branch the mob object now has a usage_code property

**Comment by rolodub** [comment]
Thanks a lot for all your work!
