### ISSUE TITLE
Fix setup.py for windows

### ISSUE THREAD

**Issue by markreidvfx** [markreidvfx/pyaaf#3]
need to provide some better docs for building on windows

requirements:
   - cython >= 0.19
   - microsoft visual studio >= 2008 (professional edition need for x64)

setup.py should also just work for windows as well, right now you have to do in 3 steps

SET AAF_ROOT=C:\path\to\AAF-devel-libs-Win-1.1.6.0.Win32
python setup.py cythonize
python setup.py build_ext
python setup.py install

**Comment by cman122887** [comment]
So glad I looked into the Issues section for this. I was having trouble for some time.
Thanks for posting this.

**Comment by markreidvfx** [comment]
I have it building a lot nicer on windows in the dev branch, and in there are some building tips in the dev branch docs too.
https://github.com/markreidvfx/pyaaf/blob/dev/docs/index.rst#building-from-source

I was also planing merging dev soon, doing a 0.9 release (with windows wheels too), when I get some time to do it.

**Comment by cman122887** [comment]
Thanks for the info! Looking forward to 0.9.
