### ISSUE TITLE
How to add input_segments to an OperationGroup

### ISSUE THREAD

**Issue by cccross** [markreidvfx/pyaaf#39]
Beginner at aaf files,  I was trying to  add an  input_segment to an OperationGroup, but it seems there is no method to do that.  I am forgetting something. Could you please help me with this?

**Comment by markreidvfx** [comment]
Yes, looks like the object is missing a couple helper methods.
http://aaf.sourceforge.net/docs/aafapiman/interfaceIAAFOperationGroup.html
You could try modifying it via properties.  Try looking at operation_group_obj['InputSegments'].value . Regardless, I'll try adding the missing methods when I get a chance.

**Comment by cccross** [comment]
I created a PR, https://github.com/markreidvfx/pyaaf/pull/40. I guess that is what I needed and also can help someone else.

**Comment by markreidvfx** [comment]
I was just about to merge your pull request and realized I was looking at the master branch,
that append method is already there in the dev
https://github.com/markreidvfx/pyaaf/blob/dev/aaf/component/OperationGroup.pyx#L76
insert is there too, 
https://github.com/markreidvfx/pyaaf/blob/dev/aaf/component/OperationGroup.pyx#L79

sorry for the confusion

**Comment by markreidvfx** [comment]
I also just added the remove method too
https://github.com/markreidvfx/pyaaf/blob/dev/aaf/component/OperationGroup.pyx#L82

**Comment by cccross** [comment]
I was looking at the master branch too. Thanks for the clarification.
