### ISSUE TITLE
Media Composer thinks media is wrong format when linking

### ISSUE THREAD

**Issue by ding-hub** [markreidvfx/pyaaf#42]
I've been trying to get an aaf file with linked mxf following the example baselight_multiaaf.py but the problem is that even though the mxf is correct (145 1080i) when I use the AMA plugin, when I use the script media composer thinks the file is 1:1 1080p and refuses to play the files. It gives me error "Exception: The sequence or one of its source elements is too long to be played" I would like to know if anyone has had success using a linked xmf. I have been spending so much time trying to get this to work without any success. I have even tried to add a TapeDescriptor along with the CDCIDescriptor with no joy. I have even used the baselight_multiaaf.py and had no luck. Any help would be greatly appreciated.

**Comment by markreidvfx** [comment]
Could you provide a sample of AAF file of what your trying to match?

**Comment by ding-hub** [comment]
sure.
[MatteTest.mov (With Alpha).aaf.zip](https://github.com/markreidvfx/pyaaf/files/1463537/MatteTest.mov.With.Alpha.aaf.zip)

**Comment by ding-hub** [comment]
Im trying to do this
https://github.com/markreidvfx/pyaaf/issues/41
but with linked mxf files instead of importing the essence

**Comment by ding-hub** [comment]
here is what the code looks like.
```
def add_clips(path, frame_rate):
    data = probe(path)
    filename = ntpath.basename(path)
    
    format = data['format']
    metadata = format['tags']
    stream = data['streams'][0]
    stream_metadata = stream['tags']

    file_package_umid = stream_metadata['file_package_umid']
    material_name = metadata['material_package_name']
    file_package_name = 'file_package_name'

    file_package_mob_id, reel_mob_id,clip_start_timecode = mxfinfo(path)
    codec_type = stream['codec_type']
    rate = fractions.Fraction(stream['avg_frame_rate'])
    duration = stream['duration_ts']
    
    media_kind = "picture"
    width = int(stream['width'])
    height = int(stream['height'])
        
    mastermob = f.create.MasterMob(material_name)
    print material_name
    mastermob['AppCode'].value = 1
    f.storage.add_mob(mastermob)
    
    media_kind = "picture"
    width = int(stream['width'])
    height = int(stream['height'])

    descriptor = f.create.CDCIDescriptor()

    descriptor['ImageAspectRatio'].value = fractions.Fraction(width, height)
    descriptor['FrameLayout'].value = 'SeparateFields'
    descriptor['StoredWidth'].value = width
    descriptor['StoredHeight'].value = height
    descriptor['Length'].value = duration
    descriptor['SampleRate'].value = rate
    
    loc = f.create.NetworkLocator()
    loc.path = 'file:///Work/Avid%20MediaFiles/MXF/1/' + filename
    descriptor.append_locator(loc)
    
    src_mob = f.create.SourceMob(file_package_name)
    src_mob.mobID = file_package_mob_id
    src_mob.essence_descriptor = descriptor
    src_mob.add_nil_ref(1, duration, media_kind, rate)
    f.storage.add_mob(src_mob)

    source_clip = src_mob.create_clip(1)

    mastermob.append_new_timeline_slot(rate, source_clip, 1)
    clip = mastermob.create_clip(1)
    
    clip_type = 'Source'
    
    if '_alpha.mxf' in filename:
        clip_type = 'Alpha'
    
    composite[clip_type] = clip
    return duration

# CREATE NESTED SCOPE FOR ALPHA CHANNEL EFFECT
scopesequence = f.create.Sequence("picture")
opgroup.insert(0, scopesequence)
scope = aaf.component.NestedScope(f, "picture", 30)
scopesequence.append(scope)
length = 0

for path in filelist:
    if '.mxf' in path:
        path=os.path.join(folderpath,path)
        length = add_clips(path, 29.97)
print length

opgroup.insert(1, composite["Source"])
opgroup.insert(2, composite["Alpha"])
```

**Comment by ding-hub** [comment]
the error I'm getting is actually
"Exception: MXF_DIDMapperSegmented::GetParsedIndexTableSegmented - Unable to parse the Index Table"
the previous error was a framerate problem I posted by mistake

**Comment by ding-hub** [comment]
What is interesting is if I delete the clips in my bin and delete the database files and use the media tool I can see the mxf's and play them back properly as dnxhd 145 but as soon as I delete the database file again and import the aaf avid gets confused again and thinks the files are 1:1 and wont play them back. Its like the aaf forces the database to see these files in a different format.

**Comment by markreidvfx** [comment]
I haven't had a chance to look into this, but my initial hunch is the compression ID on the descriptor.  I have a list based off the CID in pyaaf2 [here](https://github.com/markreidvfx/pyaaf2/blob/master/aaf2/video.py#L84). CID is in the header of the raw dnxhd frame. You can also match AUIDs from a aaf exported from media composer.

**Comment by ding-hub** [comment]
Gave it a go with no joy.
`descriptor['Compression'].value = uuid.UUID("04010202-7108-0000-060e-2b340401010a")`
it matches the original xml but it doesnt work. The interesting thing is if I clear the database and look in the media tool and play back the mxf from the media tool then when I bring the oaf in it knows its correct format but if I delete the databases again and just bring in the aaf it gets confused again. Its super confusing but the aaf is not relaying the correct format info to avid.

**Comment by ding-hub** [comment]
The only odd thing is that the CID from the xml I create from my aaf has this.
`<SourcePackageID>urn:smpte:umid:00000000.00000000.00000000.00000000.00000000.00000000.00000000.00000000</SourcePackageID>`
I dont think that has anything to do with my problem but just in case.

**Comment by ding-hub** [comment]
ok I've been shooting in the dark here trying random things and when I use this...
`descriptor['FrameSampleSize'].value = 606208`
I'm getting the right format in avid but I get a FATAL_ERROR warning and the clips wont play back

> Exception caught in APlayer::Play - Exception: FATAL_ERROR, msg:Assertion failed: FALSE, file:/Snapshots/relengmini2_1501637147/coresw/ame/src/Consumers/Devices/SWCodecInterface.cpp, line:533
