### ISSUE TITLE
Calculate and add aux timecodes to aaf

### ISSUE THREAD

**Issue by ilansr** [markreidvfx/pyaaf#45]
Hi Mark,
I am trying to add aux timecodes to my aaf file and would very much appreciate any help i can get.

I am attaching an example to what I mean.
In the example, the Master Time starts at tc 20:00:00. The desired output should arrange the Aux TC accordingly. I know that in theory I am supposed to run through the sequence and set the aux tc to where each clip begins.
 
The following zip contains the following files:
SYNC_NEW- no AuxTC.aaf - This file is an input (does not contain Aux TC)
SYNC_NEW - AuxTC.aaf - This file is the above input post manual addition of Aux TC via Avid
[input and output.zip](https://github.com/markreidvfx/pyaaf/files/1636988/input.and.output.zip)

This is what the channels look like:
![image](https://user-images.githubusercontent.com/4265549/35014460-55773280-fb19-11e7-9e00-f08a4f75a71c.png)

This is how the output should look like on Avid:
![image](https://user-images.githubusercontent.com/4265549/35014541-907d9a5e-fb19-11e7-9781-badd78f1f04e.png)

Once again, thank you in advance for any advice possible
Ilan

**Comment by ilansr** [comment]
Hi @markreidvfx 
Friendly reminder :)
Any help / pointers would be appreciated
Thanks!

**Comment by gone-fishing** [comment]
Hi ilansr, how did you go with this? I am working on a similar thing

**Comment by bcvery1** [comment]
@ilansr Why did this get closed, can you provide the solution you found?  This is exactly what I'm trying and failing to do currently.  Thanks!

Failing a response, @markreidvfx are you able to assist here, please?

**Comment by bcvery1** [comment]
@gone-fishing I don't know if this is still relevant to you, but I have had some progress.  By calling `.create_timecode_slot(...)` on the source mob twice, (I do not know what the first call is setting), the `Auxiliary TC1` column is set to `00:00:00:00`

**Comment by gone-fishing** [comment]
thanks bcvery1. I have had a little bit of success. I'm on holidays at the moment so i am trying to remember. here is how I remember it. I used this ... https://github.com/markreidvfx/pyaaf/blob/master/example/import_media.py 
specifically the 
def add_tape(f, source_clip, tape_name, frame_rate, timecode_fps=24):
part

then on this tape mob there should be a property called ‘PhysicalTrackNumber’
the specifies what type of timecode it is. you can look up in the avid aaf specifications doc what the PhysicalTrackNumber is meant to be for for the auxiliary TC1. I don’t have that doc on me but I think its mentioned in pyaaf documentation.
I wanted to use auxiliary track 3 which has a PhysicalTrackNumber of 5 so I did something like this
i['PhysicalTrackNumber'].value = 5
sorry I cant be more specific. but if you can follow this and iterate thru the keys of the tape mob I think you will get there. And huge caveat, I am not trained in any way in coding, Im a complete hack so I could be doing this all a very stupid way.
if you do come up with a better way Id love to know. cheers
