### ISSUE TITLE
ImportError: No module named Cython.Build

### ISSUE THREAD

**Issue by MartinDelille** [markreidvfx/pyaaf#48]
When I try to compile pyaaf, it fails:

```
$ python setup.py build_ext --inplace
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    from Cython.Build import cythonize
ImportError: No module named Cython.Build
```

**Comment by markreidvfx** [comment]
Looks to me like cython is missing, what version of cython do you have installed?

**Comment by MartinDelille** [comment]
```
$ cython --version
Cython version 0.28.5
```

**Comment by markreidvfx** [comment]
Looks really strange, are you able to run this in python?
```
from Cython.Build import cythonize
```
Maybe cython isn't in your PYTHONPATH ?

**Comment by MartinDelille** [comment]
Ok the problem was that I installed *Cython* with `pip3` and that `python --version` returns `2.7.10`
